Fix loading Engelsystem shifts.
+ Due to a version increase of Moshi from 1.9.3 to 1.11.0 in
  ef53203d3e73e92f0947387e0b1e4253aca01726 and the fact that ProGuard
  rules are auto-generated as of Moshi 1.10.0 the generated ShiftJsonAdapter
  class was suddenly missing.
+ This commit adds the formerly provided ProGuard rules - copied from:
  https://raw.githubusercontent.com/square/moshi/moshi-parent-1.9.3/moshi/src/main/resources/META-INF/proguard/moshi.pro
  These can be removed once the Engelsystem library uses Moshi 1.10.0+
  itself.
+ Related commit: b87b2867c748efc047e0f0741ddb53764f76a134.

Original error message (from stacktrace):

  java.lang.IllegalArgumentException: Unable to create converter for java.util.List<info.metadude.kotlin.library.engelsystem.models.Shift>
  java.lang.RuntimeException: Failed to find the generated JsonAdapter class for class info.metadude.kotlin.library.engelsystem.models.Shift
  java.lang.ClassNotFoundException: info.metadude.kotlin.library.engelsystem.models.ShiftJsonAdapter
  java.lang.ClassNotFoundException: Didn't find class "info.metadude.kotlin.library.engelsystem.models.ShiftJsonAdapter"

Resolves #338