Fix crash at reboot (OnBootReceiver).
+ Error:

  RuntimeException: Unable to start receiver nerd.tuxmobil.fahrplan.congress
    .system.OnBootReceiver: kotlin.UninitializedPropertyAccessException:
    lateinit property alarmsDatabaseRepository has not been initialized
  Caused by: kotlin.UninitializedPropertyAccessException: lateinit property
    alarmsDatabaseRepository has not been initialized
    at nerd.tuxmobil.fahrplan.congress.repositories.AppRepository.readAlarms(SourceFile:710)