Fix crash at startup on tablets due to incomplete layout file.
+ Broken since: 864eca70005265142e495b87ec0ec18db0e52248
+ Stacktrace:

  java.lang.IllegalArgumentException: ID does not reference a View inside this Activity
    at android.app.Activity.requireViewById(Activity.java:3733)
    at androidx.core.app.ActivityCompat$Api28Impl.requireViewById(ActivityCompat.java:877)
    at androidx.core.app.ActivityCompat.requireViewById(ActivityCompat.java:361)
    at nerd.tuxmobil.fahrplan.congress.base.BaseActivity.requireViewByIdCompat(BaseActivity.kt:74)
    at nerd.tuxmobil.fahrplan.congress.schedule.MainActivity.access$requireViewByIdCompat(MainActivity.kt:68)
    at nerd.tuxmobil.fahrplan.congress.schedule.MainActivity$observeViewModel$4.emit(MainActivity.kt:190)
    at nerd.tuxmobil.fahrplan.congress.schedule.MainActivity$observeViewModel$4.emit(MainActivity.kt:189)
    at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:401)
    at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)
    ...