Prevent crash when loaded schedule does not contain any session.
+ Error:
  NullPointerException: Parameter specified as non-null is null: method
  kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter
  conference
  E  at TimeTextViewParameter$Companion.parametersOf(TimeTextViewParameter.kt)
  E  at TimeTextViewParameter.parametersOf(TimeTextViewParameter.kt)
  E  at FahrplanFragment.fillTimes(FahrplanFragment.java:490)