Fix crash when rotating tablet from portrait to landscape orientation.
+ Broken since: 6afc02da7b4f7b512daabeb93eb10590eff8fcb8
+ Stacktrace:

java.lang.IllegalArgumentException: Wrong state class, expecting View State
but received class androidx.coordinatorlayout.widget.CoordinatorLayout$SavedState
instead. This usually happens when two views of different type have the same id
in the same hierarchy. This view's id is id/root_layout. Make sure other views
do not use the same id.

  at android.view.View.onRestoreInstanceState(View.java:23552)
  at android.view.View.dispatchRestoreInstanceState(View.java:23524)
  at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4247)
  at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4253)
  at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4253)
  at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4253)
  at android.view.View.restoreHierarchyState(View.java:23502)
  at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2284)
  at android.app.Activity.onRestoreInstanceState(Activity.java:1913)
  at android.app.Activity.performRestoreInstanceState(Activity.java:1866)
  ...