Fix crash at app start on devices running Android before Pie 9 (API 28).
+ Broken since: e7d4f7605378ea6dbaa73f5ad6f45b66d1adbee2
+ Activity#requireViewById was added in Android 9 (API 28)
  https://developer.android.com/reference/android/app/Activity#requireViewById(int)

+ Stacktrace:

  java.lang.NoSuchMethodError: No virtual method requireViewById(I)Landroid/view/View;
  in class Landroidx/fragment/app/FragmentActivity; or its super classes (declaration
  of 'androidx.fragment.app.FragmentActivity' appears in /data/app/
  info.metadude.android.congress.schedule.debug-kTe9z-9HQ_bn82E5_R3DtQ==/base.apk:classes30.dex)
    at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanFragment$observeViewModel$4.emit(FahrplanFragment.kt:281)
    at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanFragment$observeViewModel$4.emit(FahrplanFragment.kt:280)
    at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:401)
    at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)
    at info.metadude.android.eventfahrplan.commons.flow.FlowExtensionsKt$observe$1$1.invokeSuspend(FlowExtensions.kt:14)
    at info.metadude.android.eventfahrplan.commons.flow.FlowExtensionsKt$observe$1$1.invoke(Unknown Source:8)
    at info.metadude.android.eventfahrplan.commons.flow.FlowExtensionsKt$observe$1$1.invoke(Unknown Source:4)
    at androidx.lifecycle.RepeatOnLifecycleKt$repeatOnLifecycle$3$1$1$1$1$1$1.invokeSuspend(RepeatOnLifecycle.kt:110)
    ...

+ Successfully tested on Android 8.0, API 26 (Oreo) emulator.